# 파일 규격 버전
version: '2.2'
# 컨테이너 정의
services:
  elasticsearch:
    # container 생성시 사용 할 이미지를 지정한다. [image 이름]:[버전]
    # image: 'docker.elastic.co/elasticsearch/elasticsearch:7.7.1'
    build:
      # 도커파일의 위치 알려주기
      context: .
      # 인자 넣어주기
      args:
        ELK_VERSION: 7.7.1
    container_name: es01
    # 엘라스틱 환경 설정
    environment:
      # 노드 이름
      - node.name=es01
      # 클러스터명 (클러스터명을 기준으로 노드가 join 한다)
      - cluster.name=es-docker-cluster
      # 디스커버리 설정, 클러스터를 구성할 노드에 대한 정의
      - discovery.seed_hosts=es02,es03
      # 마스터로 선출될 후보 노드 초기 세팅 (node.name 참조)
      - cluster.initial_master_nodes=es01,es02,es03
      # 엘라스틱이 사용할 메모리 Lock
      - bootstrap.memory_lock=true
      # jvm이 사용 가능한 힙 사이즈 결정
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # 프로세스 자원 한도 설정
    ulimits:
      # 메모리 내 주소 공간의 최대 크기 (soft: 기본 적용 값, hard: soft에서 최대로 늘릴 한도)
      memlock:
        soft: -1
        hard: -1
    # 공유 볼륨 설정
    volumes:
      - data01:/usr/share/elasticsearch/data
    # 공유할 포트 설정 (로컬 포트:컨테이너 포트)
    ports:
      - "127.0.0.1:9200:9200"
    # 하나의 네트워크로 통신하기 위해 현재 elastic으로 모두 지정
    # driver : bridge, host, container, none 이렇게 4개가 존재함 (default는 bridge)
    networks:
      - elastic
  es02:
    # image: 'docker.elastic.co/elasticsearch/elasticsearch:7.7.1'
    build:
      # 도커파일의 위치 알려주기
      context: .
      # 인자 넣어주기
      args:
        ELK_VERSION: 7.7.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    # image: 'docker.elastic.co/elasticsearch/elasticsearch:7.7.1'
    build:
      # 도커파일의 위치 알려주기
      context: .
      # 인자 넣어주기
      args:
        ELK_VERSION: 7.7.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  kib01:
    #  키바나 공식 이미지 사용 (엘라스틱과 버전 동일)
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: kib01
    # 포트 포워딩을 위한 포트 지정 (기본 포트 5601)
    ports:
      - 5601:5601
    # 엘라스틱에 연결하기 위한 URL과 HOST 지정
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    # 다른 엘라스틱 컨테이너와 동일 한 네트워크 설정
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge